### ISSUE TITLE
Add a blogroll

### ISSUE THREAD

**Issue by Quiroptero** [Quiroptero/source.omiranda.dev#4]
Totally inspired by https://www.lkhrs.com/blogroll/

**Comment by Ananya2001-an** [comment]
Hey! Can you assign this to me?

**Comment by Quiroptero** [comment]
> Hey! Can you assign this to me?

Hi @Ananya2001-an , thanks for reaching out.

This repo holds the source files for building my personal website, so it wouldn't make much sense to assign you this issue. I'm actually using Github's issue system as a kind of to-do list.

Perhaps you would like to contribute to the **LoveIt** Github theme codebase by raising a pull request or filing an issue. You can find that repo here: https://github.com/dillonzq/LoveIt

**Comment by Ananya2001-an** [comment]
Hi @Quiroptero . 
Thanks for replying.  I am actually interested to contribute to the love it theme repository but since I am very new to open source hence I don't know how to do it. What I mean to say is I don't know what are some good beginner level issues that I can handle. If you can guide me about it, I will be really grateful.

**Comment by Quiroptero** [comment]
Hi @Ananya2001-an 

The following are advice from my experience, you might or might not follow them:

- The first thing is to actually use the product/app/plugin/whatever that you want to contribute to. This has two main reasons: a) you can spot some bugs or weird behaviors; b) as a user, you will eventually miss some features, so you will have an idea of what to build next
- There's no such thing as a minimum entry level. What I mean is that you can contribute as much as you want or can. Fixing a typo in the documentation is already good enough.
- Many open source projects have a roadmap/issue tracker embedded and many of those systems are labeled, so you can search for pending items that you can handle. For instance, a common label in Github repos is the `good first issue` one, so you can filter those issues and pick the one that catches your attention to work with.

As summary, in my opinion there's no better way to contribute to open source projects than using the product and then building on top of it the features that you would like to have.

If you are looking forward to contribute to the LoveIt Hugo theme you should create a Hugo site and use that theme first :slightly_smiling_face:

**Comment by Ananya2001-an** [comment]
@Quiroptero Thanks for the great advice.
😊

**Comment by Quiroptero** [comment]
First implementation of the blogroll can be found [here](https://omiranda.dev/blogroll/).
Layout customization will be left for later.
